/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:d1c531d0-67c1-4129-8d88-93c381911fe5",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_FKWdItGrj",
    "aws_user_pools_web_client_id": "4bjdsb83f5vhjnfs3dqp8k4fuh",
    "oauth": {},
    "aws_mobile_analytics_app_id": "60769fe3ab694387a8b869483cd8b303",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
